const zh=document.body.dataset.lang==='zh';
const t=(a,b)=>zh?a:b;
const modules=new Map(Object.entries({
 'plus':[['path',{d:'M12 5v14M5 12h14'}]],'minus':[['path',{d:'M5 12h14'}]],
 'arrow-right':[['path',{d:'M5 12h14m-6-6 6 6-6 6'}]],'chevron-down':[['path',{d:'m6 9 6 6 6-6'}]],
 'copy':[['rect',{x:'9',y:'9',width:'11',height:'11',rx:'2'}],['path',{d:'M15 9V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v9a1 1 0 0 0 1 1h4'}]]
}));
async function paintIcons(root=document){for(const el of root.querySelectorAll('[data-icon]')){const name=el.dataset.icon;try{if(!modules.has(name))modules.set(name,(await import(`./assets/icons/${name}.js`)).default);if(!el.isConnected)continue;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');for(const[k,v]of Object.entries({viewBox:'0 0 24 24',fill:'none',stroke:'currentColor','stroke-width':'1.5','stroke-linecap':'round','stroke-linejoin':'round','aria-hidden':'true'}))svg.setAttribute(k,v);for(const[tag,attrs]of modules.get(name)){const path=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))path.setAttribute(k,v);svg.append(path);}el.replaceChildren(svg);}catch{el.hidden=true;}}}
const menu=document.querySelector('#site-menu'),menuButton=document.querySelector('[data-menu-toggle]');
menuButton.addEventListener('click',()=>{menu.showModal();menuButton.setAttribute('aria-expanded','true');});
document.querySelector('[data-menu-close]').addEventListener('click',()=>menu.close());
menu.addEventListener('click',e=>{if(e.target===menu&&e.clientX<menu.getBoundingClientRect().left)menu.close();});
menu.addEventListener('close',()=>{menuButton.setAttribute('aria-expanded','false');menuButton.focus();});
function preference(key){try{return localStorage.getItem(key);}catch{return null;}}
function savePreference(key,value){try{localStorage.setItem(key,value);}catch{}}
document.body.dataset.theme=preference('tyh-theme')||'light';
document.body.dataset.largeText=preference('tyh-large-text')||'false';
const themeButton=document.querySelector('[data-theme-toggle]'),sizeButton=document.querySelector('[data-text-size]');
themeButton.setAttribute('aria-pressed',String(document.body.dataset.theme==='dark'));
themeButton.addEventListener('click',()=>{const dark=document.body.dataset.theme!=='dark';document.body.dataset.theme=dark?'dark':'light';document.querySelector('meta[name="theme-color"]').content=dark?'#222222':'#f0efeb';themeButton.setAttribute('aria-pressed',String(dark));savePreference('tyh-theme',document.body.dataset.theme);});
sizeButton.setAttribute('aria-pressed',document.body.dataset.largeText);
sizeButton.addEventListener('click',()=>{document.body.dataset.largeText=String(document.body.dataset.largeText!=='true');sizeButton.setAttribute('aria-pressed',document.body.dataset.largeText);savePreference('tyh-large-text',document.body.dataset.largeText);window.ScrollTrigger?.refresh();});
const music=document.querySelector('#music'),musicButton=document.querySelector('[data-music-toggle]'),audioStatus=document.querySelector('[data-audio-status]');
const musicDock=document.querySelector('.music-dock'),musicPanel=document.querySelector('#music-panel'),musicSeek=document.querySelector('[data-music-seek]'),musicVolume=document.querySelector('[data-music-volume]');
music.volume=.55;
const audioTime=seconds=>`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
function audioState(){musicButton.setAttribute('aria-pressed',String(!music.paused));musicButton.setAttribute('aria-label',music.paused?t('播放音乐试听','Play music preview'):t('暂停音乐试听','Pause music preview'));musicButton.querySelector('[data-icon]').dataset.icon=music.paused?'play':'pause';musicDock.dataset.playing=String(!music.paused);document.querySelector('[data-music-label]').textContent=music.paused?t('听点音乐','A little music'):t('正在播放 · 尘大师','Playing · 尘大师');paintIcons(musicButton);}
function audioProgress(){const duration=Number.isFinite(music.duration)?music.duration:0;musicSeek.disabled=!duration;musicSeek.max=duration||30;musicSeek.value=music.currentTime;document.querySelector('[data-music-elapsed]').textContent=audioTime(music.currentTime);if(duration)document.querySelector('[data-music-duration]').textContent=audioTime(duration);}
musicSeek.addEventListener('input',()=>{if(Number.isFinite(music.duration))music.currentTime=Number(musicSeek.value);audioProgress();});
musicVolume.addEventListener('input',()=>{music.volume=Number(musicVolume.value);});
for(const name of ['loadedmetadata','durationchange','timeupdate'])music.addEventListener(name,audioProgress);
musicPanel.addEventListener('toggle',()=>{document.querySelector('.music-launcher').setAttribute('aria-expanded',String(musicPanel.matches(':popover-open')));});
musicButton.addEventListener('click',async()=>{if(!music.paused)music.pause();else try{audioStatus.textContent=t('加载试听…','Loading preview…');await music.play();audioStatus.textContent=t('约 30 秒官方试听','~30-second official preview');}catch{audioStatus.textContent=t('暂时无法播放试听','Preview unavailable');}});
for(const name of ['play','pause','ended'])music.addEventListener(name,audioState);
music.addEventListener('error',()=>{audioStatus.textContent=t('试听连接暂不可用','Preview connection unavailable');});
const contactPanel=document.querySelector('#contact-panel');
document.addEventListener('click',e=>{if(e.target.closest('[popovertarget="contact-panel"]')&&menu.open)menu.close();});
document.querySelector('[data-copy-email]').addEventListener('click',async()=>{const status=document.querySelector('[data-copy-status]');try{await navigator.clipboard.writeText('tin-yeh.huang@connect.polyu.hk');status.textContent=t('邮箱已复制','Email copied');}catch{status.textContent=t('请选中上方邮箱复制','Select the email above to copy it');}});
let viewAbort,animationContext,selectCurrentOrg;
function revealHash({scroll=true}={}){const id=decodeURIComponent(location.hash.slice(1));if(!id)return;if(id==='contact'){contactPanel.showPopover();return;}if(id.startsWith('org-')){selectCurrentOrg?.(id.slice(4),false);if(scroll)document.querySelector('.background-board')?.scrollIntoView({block:'start',behavior:'instant'});return;}const target=document.getElementById(id);if(!target)return;if(target.matches('[data-background-item]'))selectCurrentOrg?.(target.dataset.organisations.split(' ')[0],false);if(target.hidden&&target.matches('.entry')){target.hidden=false;document.querySelector('[data-result-count]').textContent=`${document.querySelectorAll('.entry:not([hidden])').length} ${t('项内容','entries')}`;}const disclosure=target.matches('.entry')?target.querySelector('[data-entry]'):null;if(disclosure)disclosure.open=true;for(let parent=target.parentElement;parent;parent=parent.parentElement)if(parent instanceof HTMLDetailsElement)parent.open=true;if(target instanceof HTMLDetailsElement)target.open=true;if(scroll)target.scrollIntoView({block:'start',behavior:'instant'});}
function initialiseView({scrollToHash=true}={}){
 viewAbort?.abort();animationContext?.revert();viewAbort=new AbortController();const options={signal:viewAbort.signal};const main=document.querySelector('main');paintIcons(main);
 const collection=main.querySelector('.collection');
 if(collection){const search=collection.querySelector('[data-search-input]'),buttons=collection.querySelectorAll('[data-filter]');const params=new URLSearchParams(location.search);let filter=[...buttons].some(b=>b.dataset.filter===params.get('filter'))?params.get('filter'):'all';search.value=params.get('q')||'';const sort=collection.querySelector('[data-sort]');sort.value=params.get('sort')==='newest'?'newest':'curated';function update(){let n=0;const q=search.value.trim().toLowerCase();for(const row of collection.querySelectorAll('[data-search]')){row.hidden=!(row.dataset.search.includes(q)&&(filter==='all'||row.dataset.tags.split(' ').includes(filter)));if(!row.hidden)n++;}const result=collection.querySelector('[data-results]');const ordered=[...result.children].sort((a,b)=>sort.value==='newest'?Number(b.dataset.date)-Number(a.dataset.date)||Number(a.dataset.order)-Number(b.dataset.order):Number(a.dataset.order)-Number(b.dataset.order));result.append(...ordered);collection.querySelector('[data-result-count]').textContent=`${n} ${t('项内容',n===1?'entry':'entries')}`;collection.querySelector('.empty-state').hidden=n>0;for(const b of buttons)b.setAttribute('aria-pressed',String(b.dataset.filter===filter));const url=new URL(location.href);if(q)url.searchParams.set('q',search.value);else url.searchParams.delete('q');if(filter!=='all')url.searchParams.set('filter',filter);else url.searchParams.delete('filter');const active=url.hash?collection.querySelector('#'+CSS.escape(decodeURIComponent(url.hash.slice(1)))):null;if(active?.hidden)url.hash='';if(sort.value!=='curated')url.searchParams.set('sort',sort.value);else url.searchParams.delete('sort');history.replaceState(history.state,'',url);}sort.addEventListener('change',update,options);search.addEventListener('input',update,options);for(const b of buttons)b.addEventListener('click',()=>{filter=b.dataset.filter;update();},options);update();}
 selectCurrentOrg=null;
 const board=main.querySelector('.background-board');
 if(board){selectCurrentOrg=(id,write=true)=>{const selected=board.querySelector(`[data-org="${CSS.escape(id)}"]`);if(selected?.hidden){for(const org of board.querySelectorAll('[data-city-group]'))org.hidden=false;for(const city of board.querySelectorAll('[data-city]'))city.setAttribute('aria-pressed',String(city.dataset.city==='all'));board.querySelector('.board-secondary').hidden=false;}let n=0;for(const row of board.querySelectorAll('[data-background-item]')){row.hidden=!id||!row.dataset.organisations.split(' ').includes(id);if(!row.hidden)n++;}for(const button of board.querySelectorAll('[data-org]')){button.setAttribute('aria-pressed',String(button===selected));button.setAttribute('aria-expanded',String(button===selected));}board.querySelector('.selected-institution').hidden=!id;board.querySelector('[data-close-org]').hidden=!id;board.querySelector('.board-empty').hidden=!!id;const panel=board.querySelector('#organisation-context'),choices=board.querySelector('.organisation-choices'),layout=board.querySelector('.background-layout');if(matchMedia('(max-width:600px)').matches&&selected&&choices.contains(selected)){const cells=[...choices.querySelectorAll(':scope>button:not([hidden])')],index=cells.indexOf(selected),rowEnd=cells[Math.min(Math.floor(index/3)*3+2,cells.length-1)];rowEnd.after(panel);}else if(panel.parentElement!==layout)layout.append(panel);board.querySelector('[data-selected-org]').textContent=selected?.dataset.orgName||'';board.querySelector('[data-background-count]').textContent=`${n} ${t('项记录',n===1?'record':'records')}`;if(write){const url=new URL(location.href);url.hash=id?'org-'+id:'';history.replaceState({...history.state,scroll:scrollY},'',url);}window.ScrollTrigger?.refresh();};for(const button of board.querySelectorAll('[data-org]'))button.addEventListener('click',()=>selectCurrentOrg(button.getAttribute('aria-pressed')==='true'?'':button.dataset.org),options);board.querySelector('[data-close-org]').addEventListener('click',()=>{const button=board.querySelector('[data-org][aria-pressed="true"]');selectCurrentOrg('');button?.focus({preventScroll:true});},options);selectCurrentOrg('',false);for(const city of board.querySelectorAll('[data-city]'))city.addEventListener('click',()=>{const id=city.dataset.city;selectCurrentOrg('');for(const item of board.querySelectorAll('[data-city]'))item.setAttribute('aria-pressed',String(item.dataset.city===id));for(const org of board.querySelectorAll('[data-city-group]'))org.hidden=id!=='all'&&org.dataset.cityGroup!==id;board.querySelector('.board-secondary').hidden=id!=='all';board.dataset.city=id;},options);window.addEventListener('resize',()=>{const selected=board.querySelector('[data-org][aria-pressed="true"]');if(selected)selectCurrentOrg(selected.dataset.org,false);},options);}
 for(const disclosure of main.querySelectorAll('[data-entry]')){disclosure.addEventListener('toggle',()=>{if(disclosure.open&&window.gsap&&!matchMedia('(prefers-reduced-motion:reduce)').matches)gsap.fromTo(disclosure.querySelector('.entry-body'),{opacity:.4},{opacity:1,duration:.2,overwrite:true});const url=new URL(location.href);if(disclosure.open)url.hash=disclosure.dataset.entry;else if(url.hash==='#'+disclosure.dataset.entry)url.hash='';history.replaceState({...history.state,scroll:scrollY},'',url);window.ScrollTrigger?.refresh();},options);disclosure.querySelector('[data-close-entry]').addEventListener('click',()=>{disclosure.open=false;disclosure.querySelector('summary').focus({preventScroll:true});},options);}
 if(new URLSearchParams(location.search).get('contact')==='open')contactPanel.showPopover();
 for(const button of main.querySelectorAll('[data-work-area]'))button.addEventListener('click',()=>{for(const b of main.querySelectorAll('[data-work-area]'))b.setAttribute('aria-pressed',String(b===button));for(const panel of main.querySelectorAll('[data-work-panel]'))panel.hidden=panel.dataset.workPanel!==button.dataset.workArea;},options);
 updateClock();
 if(window.gsap&&window.ScrollTrigger){gsap.registerPlugin(ScrollTrigger);animationContext=gsap.context(()=>{const mm=gsap.matchMedia();mm.add('(min-width:601px) and (prefers-reduced-motion:no-preference)',()=>{const image=main.querySelector('.material-scene img');if(image)gsap.to(image,{y:28,scale:1.035,ease:'none',scrollTrigger:{trigger:main.querySelector('.landing'),start:'top top',end:'bottom top',scrub:.7}});const cells=main.querySelectorAll('.kernel-grid .lit');if(cells.length)gsap.fromTo(cells,{opacity:.4},{opacity:1,duration:.75,stagger:.035,scrollTrigger:{trigger:main.querySelector('.engineering-feature'),start:'top 90%',toggleActions:'play none none reverse'}});});},main);ScrollTrigger.refresh();}
 revealHash({scroll:scrollToHash});
}
function updateClock(){const clock=document.querySelector('[data-local-time]');if(clock){const now=new Date();clock.textContent=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Hong_Kong',hour:'2-digit',minute:'2-digit',hour12:false}).format(now);clock.dateTime=now.toISOString();}}
setInterval(updateClock,30000);
paintIcons();initialiseView();window.addEventListener('hashchange',revealHash);
// Keep normal HTML URLs and browser history, while retaining the player on same-language navigation.
let navigationController,navigationId=0,renderedPath=location.pathname;
history.scrollRestoration='manual';
history.replaceState({...history.state,scroll:scrollY},'');
async function navigate(url,{pop=false,scroll=0}={}){const id=++navigationId;navigationController?.abort();navigationController=new AbortController();try{const response=await fetch(url,{signal:navigationController.signal,cache:'no-cache'});if(!response.ok)throw new Error('Navigation failed');const doc=new DOMParser().parseFromString(await response.text(),'text/html');if(!doc.querySelector('main')){location.href=url;return;}if(id!==navigationId)return;if(!pop){history.replaceState({...history.state,scroll:scrollY},'');history.pushState({scroll:0},'',url);}menu.close();if(contactPanel.matches(':popover-open'))contactPanel.hidePopover();viewAbort?.abort();animationContext?.revert();document.querySelector('main').replaceChildren(...doc.querySelector('main').childNodes);document.title=doc.title;document.body.dataset.page=doc.body.dataset.page;renderedPath=new URL(url,location.href).pathname;document.querySelector('.desktop-nav').replaceChildren(...doc.querySelector('.desktop-nav').childNodes);document.querySelector('.language-link').href=doc.querySelector('.language-link').href;document.querySelector('#site-menu nav').replaceChildren(...doc.querySelector('#site-menu nav').childNodes);paintIcons(menu);paintIcons(document.querySelector('.site-header'));initialiseView({scrollToHash:!pop});if(pop||!new URL(url,location.href).hash)window.scrollTo({top:scroll,behavior:'instant'});document.querySelector('main').focus({preventScroll:true});}catch(error){if(error.name!=='AbortError')location.href=url;}}
document.addEventListener('click',e=>{const anchor=e.target.closest('a[href]');if(!anchor||e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||anchor.target||anchor.hasAttribute('download')||anchor.classList.contains('language-link'))return;const url=new URL(anchor.href),current=new URL(location.href);if(url.origin!==current.origin||url.pathname.split('/').slice(0,-1).join('/')!==current.pathname.split('/').slice(0,-1).join('/')||!url.pathname.endsWith('.html'))return;if(url.pathname===current.pathname&&url.search===current.search)return;e.preventDefault();navigate(url.href);});
window.addEventListener('popstate',e=>{if(location.pathname===renderedPath){initialiseView({scrollToHash:!!location.hash});if(!location.hash)window.scrollTo({top:e.state?.scroll||0,behavior:'instant'});return;}navigate(location.href,{pop:true,scroll:e.state?.scroll||0});});
