import {works,experiences} from './content.mjs';
import {entries} from './entries.mjs';
import {education} from '../material-demo/dist/desk-background.mjs';
import {organisations,credentials} from '../material-demo/dist/desk-affiliations.mjs';
import {mapGeometry} from './map-geometry.mjs';
import {industrialNote} from './industrial-note.mjs';
import {music} from '../material-demo/dist/desk-config.mjs';
import {venueMetrics} from './venue-metrics.mjs';
import {press} from './news.mjs';

export function createViews({lang,prefix,h,t,icon,a,cacheKey=''}){
 const pick=x=>x?.[lang]??x??'';
 const paragraphs=x=>(x??[]).map(p=>`<p>${h(p.replaceAll('这份 demo','本网站').replaceAll('this demo','this website'))}</p>`).join('');
 const arrow=()=>icon('arrow-up-right');
 const cta=(url,txt,cls='text-link')=>a(url,h(txt)+icon(/^(https?:|mailto:)/.test(url)?'arrow-up-right':'arrow-right'),cls);
 const papers=works.filter(w=>w.kind==='paper');
 const engineering=works.find(w=>w.id==='ninetoothed');
 const social=experiences.find(e=>e.id==='x-social');
 const sourceLabel=name=>{const parts=name.split(' / ');if(parts.length!==2)return name;return /[\u3400-\u9fff]/.test(parts[0])?t(parts[0],parts[1]):/[\u3400-\u9fff]/.test(parts[1])?t(parts[1],parts[0]):name;};
 const links=w=>`<div class="source-links">${(w.links??[]).map(([name,url])=>`<a href="${h(url)}" target="_blank" rel="noopener noreferrer">${h(sourceLabel(name))}${arrow()}</a>`).join('')}</div>`;
 const venueChips=w=>{const m=venueMetrics[w.id];if(!m)return '';const set=`${m.if?`<span class="chip chip-if" title="${h(m.detail[lang])}">${h(m.if)}</span>`:''}${m.rank?`<span class="chip chip-rank" title="${h(m.detail[lang])}">${h(m.rank)}</span>`:''}`;return set?`<span class="chip-set">${set}</span>`:'';};
 const venue=w=>`<div class="venue-line"><strong>${h(w.context)}</strong>${venueChips(w)}</div>`;
 const metricSource=w=>{const m=venueMetrics[w.id];return m?`<a class="metric-source" href="${h(m.source)}" target="_blank" rel="noopener noreferrer">${h(m.detail[lang])}${arrow()}</a>`:'';};
 const heading=(label,title,desc='')=>`<header class="page-heading wrap"><p class="eyebrow">${label}</p><h1>${title}</h1>${desc?`<p>${desc}</p>`:''}</header>`;
 const mark=o=>`<img class="org-mark" src="${prefix}assets/logos/${h(o.mark)}" alt="" aria-hidden="true" width="52" height="52" loading="eager">`;
 const study=e=>`<article class="study-record" id="study-${e.id}"><time>${h(e.date)}</time><div><h3>${h(pick(e.name))}</h3><p>${h(pick(e.course))}</p><small>${h(pick(e.status))} · ${e.id==='polyu'?t('Innovation & Entrepreneurship 第二专业','Secondary major: Innovation & Entrepreneurship'):h(pick(e.extra))}</small></div></article>`;
 const role=e=>{const body=pick(e.body);return `<article class="role-record" id="record-${e.id}"><header><time>${h(e.date)}</time><h3>${h(pick(e.role))}</h3><p>${h(pick(e.name))}</p></header>${paragraphs(body.slice(0,1))}${body.length>1?`<details class="role-more"><summary>${t('更多内容','More details')}</summary>${paragraphs(body.slice(1))}</details>`:''}<div class="related">${(e.related??[]).map(id=>{const w=works.find(w=>w.id===id);return cta(w?.pdf?'read-'+id+'.html':w?.kind==='paper'?'collection.html#'+id:'project-ninetoothed.html',pick(w?.title));}).join('')}${links(e)}</div></article>`;};

 const type=e=>({heatwave:t('期刊论文','Journal article'),structrace:t('已接收论文','Accepted paper'),glm7:t('学术通讯','Correspondence'),disease:t('学术短文','Letter'),oio:t('会议论文','Proceedings paper'),crypto:t('研讨会论文','Workshop paper'),olympic:t('活动论文','Affinity event paper'),ninetoothed:t('工程实践','Engineering'),social:t('社会创新','Social innovation')})[e.id]||t('工作','Work');
 const detailHref=e=>e.id==='ninetoothed'?'project-ninetoothed.html':e.id==='social'?'project-social-innovation.html':e.kind==='paper'?(e.pdf?'read-'+e.id+'.html':'work-'+e.id+'.html'):'collection.html';
 const entry=e=>`<article class="entry" id="${e.id}"><a class="entry-link" href="${detailHref(e)}" aria-label="${h(t('查看：','View: ')+pick(e.title))}"><figure class="entry-cover"><img src="${prefix}assets/${e.cover}?v=transparent2" width="720" height="450" alt="" loading="lazy"></figure><div class="entry-overview"><h3>${h(pick(e.title))}</h3><p class="entry-summary">${h(pick(e.summary))}</p><span class="entry-context">${h(e.context)}</span></div><div class="entry-facts"><span class="entry-type">${type(e)}</span><time>${h(e.year)}</time>${e.kind==='paper'?venueChips(e):''}<span class="entry-prompt" aria-hidden="true">${icon('arrow-right')}</span></div></a></article>`;
 const preview=e=>`<a class="home-work-link" href="${e.id==='ninetoothed'?'project-ninetoothed.html':'read-'+e.id+'.html'}"><figure><img src="${prefix}assets/${e.cover}?v=transparent2" width="720" height="450" alt="" loading="lazy"></figure><div><span class="eyebrow">${type(e)} · ${h(e.year)}</span><h3>${h(pick(e.title))}</h3><p>${h(pick(e.summary))}</p></div>${icon('arrow-right')}</a>`;
 const workGroup=(title,description,ids)=>`<section class="work-group" ${ids.includes('ninetoothed')?'id="practice"':''}><header class="work-group-head"><h2>${title}</h2><p>${description}</p></header><div class="index-list">${ids.map(id=>entry(entries.find(e=>e.id===id))).join('')}</div></section>`;
 const collection=()=>`${heading(t('工作成果','Work'),t('研究与工程','Research & engineering'))}<section class="collection wrap"><nav class="work-switch" aria-label="${t('工作类别','Work categories')}"><button type="button" data-work-tab="research" aria-pressed="true">${t('研究','Research')} <span>07</span></button><button type="button" data-work-tab="engineering" aria-pressed="false">${t('工程与实践','Engineering & practice')} <span>02</span></button></nav><div data-work-panel="research">${workGroup(t('期刊与会议论文','Journals & proceedings'),'', ['heatwave','structrace','glm7','disease','oio'])}${workGroup(t('研讨会与预印本','Workshops & preprints'),'', ['crypto','olympic'])}<p class="work-metric-note">${t('JIF 为期刊指标，并非论文评分；未核实的 JCR 分区不显示。会议与研讨会分开标注。','JIF describes a journal, not an article. Unverified JCR quartiles are omitted. Proceedings, workshops and affinity events are labelled separately.')}</p></div><div data-work-panel="engineering" hidden>${workGroup(t('工程与实践','Engineering & practice'),'', ['ninetoothed','social'])}</div></section>`;
 const notesPage=()=>`${heading(t('个人文字','Notes'),t('文章','Writing'))}<section class="notes-index wrap"><a class="note-feature" href="writing-modernization.html"><div class="note-feature-copy"><span class="eyebrow">${h(pick(industrialNote.category))} / ${h(industrialNote.date)}</span><h2>${h(pick(industrialNote.title))}</h2><p>${h(pick(industrialNote.summary))}</p><span class="note-draft">${t('编辑整理稿 · 待修订','Editorial draft · Awaiting revision')}</span><span class="note-read">${t('阅读文章','Read the essay')}${icon('arrow-right')}</span></div><figure><img src="${prefix}assets/${industrialNote.image}" alt="${t('关于造型、材料与选择的编辑插画','Editorial illustration about form, material and choice')}" width="1536" height="1024" loading="lazy"></figure></a></section>`;
 const honours=[['2026','最佳创意奖 · 团队奖','Best Innovation Award · Team award','“AI助力一小帮一老”创新挑战赛 · UNGLEP / 深圳零一学院','“AI for the Young and the Elderly” Innovation Challenge · UNGLEP / X-Institute Shenzhen'],['2026','Ir. Dr. Wong Tit-shing Student Exchange Scholarship','Ir. Dr. Wong Tit-shing Student Exchange Scholarship','香港理工大学工程学院','Faculty of Engineering, PolyU'],['2025','Scholarship for Student Exchange','Scholarship for Student Exchange','香港理工大学 Global Engagement Office','Global Engagement Office, PolyU'],['2024','Reaching Out Award','Reaching Out Award','香港特区政府奖学基金','HKSAR Government Scholarship Fund'],['2024','ISE Department Entry Scholarship','ISE Department Entry Scholarship','香港理工大学','The Hong Kong Polytechnic University'],['2024','Study Visit Programme Scholarship','Study Visit Programme Scholarship','理大专业及持续教育学院','PolyU CPCE']];
 const honourItem=([date,zh,en,dz,de])=>`<article><time>${date}</time><div><strong>${h(t(zh,en))}</strong><small>${h(t(dz,de))}</small></div></article>`;
 const albums=[
  {title:'U 87',artist:'Eason Chan',year:'2005',url:'https://music.apple.com/us/album/u-87/1443374875',cover:'u87.jpg'},
  {title:'CHIN UP!',artist:'Eason Chan',year:'2023',url:'https://music.apple.com/us/album/chin-up/1712647195',cover:'chin-up.jpg'},
  {title:'THE PROTÉGÉ',artist:'Gareth.T',year:'2026',url:'https://music.apple.com/us/album/the-prot%C3%A9g%C3%A9/1883630666',cover:'protege.jpg'}
 ];
 const albumSleeve=album=>`<a class="album-sleeve" href="${h(album.url)}" target="_blank" rel="noopener noreferrer" aria-label="${h(album.title+' · '+album.artist)}"><img class="album-cover" src="${prefix}assets/albums/${album.cover}" alt="${h(album.title+' · '+album.artist+' '+t('专辑封面','album cover'))}" width="200" height="200" loading="lazy"><span class="album-label"><strong>${h(album.title)}</strong><small>${h(album.artist)} · ${h(album.year)}</small></span></a>`;
 const tagsFor=(id,isStudy=false)=>organisations.filter(o=>(isStudy?o.study??[]:o.records).includes(id)).map(o=>o.id).join(' ')||'reviewing';
 const canonical=(html,id,isStudy=false)=>html.replace('<article ',`<article data-background-item="${id}" data-organisations="${tagsFor(id,isStudy)}" `);
 const cityFor=id=>['polyu','royal-plaza','hksar','cpce'].includes(id)?'hk':['smart','x-institute'].includes(id)?'sz':['tsinghua','cas','qiyuan','iluvatar'].includes(id)?'bj':'other';
 const cityLL=id=>{const c=mapGeometry.cities[{'bj':'beijing','sz':'shenzhen','hk':'hong-kong'}[id]].coordinates;return `${c[1]},${c[0]}`;};
 // Owner-verified organisation positions in WGS-84.
 const ORG_COORDS={
  polyu:[22.3036,114.1817],cpce:[22.3033,114.1930],'royal-plaza':[22.3199,114.2137],hksar:[22.2812,114.1602],
  tsinghua:[39.9999,116.3265],cas:[40.0035,116.3900],qiyuan:[40.0033,116.3340],iluvatar:[40.0048,116.3356],
  smart:[22.7660,113.9530],'x-institute':[22.7060,114.4010],'x-institute~nan':[22.5865,113.9740]
 };
 const geographicMap=()=>`<div class="city-map"><div class="city-canvas" data-citymap role="group" aria-label="${t('机构位置地图。可拖动缩放，点圆点或按城市筛选机构','Map of organisation locations. Drag to zoom, tap a dot or filter by city')}" data-orgs="${h(JSON.stringify(ORG_COORDS))}" data-city-bj="${cityLL('bj')}" data-city-sz="${cityLL('sz')}" data-city-hk="${cityLL('hk')}"></div><div class="map-panel"><span class="eyebrow" data-map-eyebrow>${t('地点总览','Place overview')}</span><strong data-map-title>${t('北京 · 深圳 · 香港','Beijing · Shenzhen · Hong Kong')}</strong><div data-map-organisations>${t('选择地图上的地区，再查看机构与经历。','Choose a region on the map to see institutions and experiences.')}</div></div><span class="map-note">${t('点击地点，查看相关机构与经历','Choose a point to see its organisation and experience')}</span></div>`;
 const about=()=>`${heading(t('关于我','About'),'Tin-Yeh Huang')}<section class="about-intro wrap"><div class="about-location"><span class="eyebrow">HONG KONG</span><button class="text-link" popovertarget="contact-panel">${t('联系我','Contact me')}${icon('plus')}</button></div><div class="about-copy"><p>${t('我在香港理工大学修读产品工程。这个网站整理了我参与的研究、工程实践、公共服务，以及一些个人文字。','I study Product Engineering at The Hong Kong Polytechnic University. This site brings together research and engineering work I have contributed to, public service, and some personal writing.')}</p><p>${t('做研究时，我参与过数据分析、图稿和论文写作；做工具时，我关心它是否真的方便别人使用。我也担任过学生代表，参与过社区和社会创新项目。','My research contributions include analysis, figures, and writing. In engineering work, I care about whether a tool is actually useful to someone. I have also served as a student representative and taken part in community and social innovation work.')}</p></div></section>
 <section class="background-board wrap" id="experience"><header class="section-heading"><div><span class="eyebrow">${t('学习与参与','Study & involvement')}</span><h2>${t('学习与经历','Study & experience')}</h2></div></header><div class="city-atlas">${geographicMap()}<div class="city-index" role="group" aria-label="${t('按机构所在城市筛选','Filter by institution city')}"><div class="city-caption"><span class="eyebrow">${t('机构所在城市','Institution cities')}</span><small>${t('点击城市，查看相关机构。','Select a city to view its institutions.')}</small></div>${[['bj',t('北京','Beijing')],['sz',t('深圳','Shenzhen')],['hk',t('香港','Hong Kong')]].map(([id,label])=>`<button data-city="${id}" aria-pressed="false"><span class="city-symbol" aria-hidden="true">●</span><span>${label}</span>${icon('arrow-right')}</button>`).join('')}<button data-city="" aria-pressed="false"><span class="city-symbol" aria-hidden="true">○</span><span>${t('总览','Overview')}</span>${icon('arrow-right')}</button></div></div><div class="directory-heading" hidden><span class="eyebrow">${t('机构','Institutions')}</span><span data-city-name></span></div><div class="background-layout" hidden><div class="institution-selector"><div class="organisation-choices" role="group" aria-label="${t('选择机构','Select an institution')}">${organisations.map(o=>`<button id="org-${o.id}" data-city-group="${cityFor(o.id)}" data-org="${o.id}" data-org-name="${h(pick(o.name))}" aria-label="${h(pick(o.name))}" aria-pressed="false" aria-expanded="false" aria-controls="organisation-context">${mark(o)}<span>${h(pick(o.name))}</span></button>`).join('')}</div></div><div id="organisation-context" class="organisation-context" role="region" aria-label="${t('机构记录','Institution records')}"><header class="selected-institution" hidden><h2 data-selected-org></h2><button data-close-org hidden aria-label="${t('返回机构列表','Back to institutions')}"><span class="close-org-text">${t('机构列表','Institutions')}</span>${icon('x')}</button></header><div class="background-record-list" id="education">${education.map(e=>canonical(study(e),e.id,true)).join('')}${experiences.filter(e=>e.id!=='academic-reviewing').map(e=>canonical(role(e),e.id)).join('')}</div><p class="board-empty" hidden>${t('选择一家机构，查看相关经历。','Choose an institution to see related experience.')}</p></div></div></section>
 <section class="personal-cabinet wrap" aria-labelledby="cabinet-title"><div class="cabinet-grid"><div class="cabinet-window"><div class="win-bar"><span class="win-dots" aria-hidden="true"><i></i><i></i><i></i></span><span class="win-title">${t('关于我','About me')}</span></div><div class="win-body cabinet-note"><span class="eyebrow">${t('工作之外','Beyond work')}</span><h2 id="cabinet-title">${t('形式、材料与使用','Form, material and use')}</h2><p>${t('我会留意造型、材料、使用和制造之间的关系。简化一件东西，有时也会删去帮助人理解它的线索。','I pay attention to the relationship between form, material, use, and making. Simplifying something can also remove a cue that helps people understand it.')}</p></div></div><div class="cabinet-shelf"><div class="cabinet-shelf-head"><span class="eyebrow">${t('常听的专辑','Albums on repeat')}</span></div><div class="album-roller" aria-label="${t('喜欢的专辑','Albums I like')}">${albums.map(albumSleeve).join('')}</div></div></div></section>
 <section class="background-records wrap"><header class="section-heading"><div><span class="eyebrow">${t('其他','More')}</span><h2>${t('荣誉与专业参与','Honours & professional involvement')}</h2></div></header><div class="records-ledger"><section class="ledger-group" id="honours"><header><h3>${t('荣誉与奖学金','Honours & scholarships')}</h3></header><div class="ledger-body"><div class="honours-items">${honours.map(honourItem).join('')}</div></div></section><section class="ledger-group" id="credentials"><header><h3>${t('会员与证书','Memberships & credentials')}</h3></header><div class="ledger-body credential-items">${credentials.map(c=>`<article><time>${h(c.date)}</time><div><strong>${h(pick(c.title))}</strong><small>${h(c.issuer)}</small></div></article>`).join('')}</div></section><section class="ledger-group" id="peer-review"><header><h3>${t('学术审稿','Academic peer review')}</h3></header><div class="ledger-body ledger-review" id="record-academic-reviewing"><div class="review-grid"><article><time>2026</time><strong>Foundation Models for Science (FM4Science)</strong><small>${t('国际学习表征会议研讨会 · ICLR 2026','Workshop at the International Conference on Learning Representations · ICLR 2026')}</small></article><article><time>2025</time><strong>AI for Math (AI4Math)</strong><small>${t('国际机器学习大会研讨会 · ICML 2025','Workshop at the International Conference on Machine Learning · ICML 2025')}</small></article><article><time>2025</time><strong>F1000Research</strong><small>${t('期刊审稿 · 公开报告可查','Journal peer review · Public report available')}</small><a href="https://f1000research.com/articles/14-245" target="_blank" rel="noopener noreferrer">${t('查看报告','Read report')}${arrow()}</a></article></div></div></section></div></section>`;
 const engineeringPage=()=>`${heading('QIYUAN × ILUVATAR COREX / 2026','NineToothed',t('工具开发与教学演示','Tool development and teaching demos'))}<div class="project-back wrap">${cta('collection.html#ninetoothed',t('返回工作','Back to Work'))}</div><article class="case-study wrap"><header class="case-opening"><div><span class="eyebrow">NINETOOTHED / 2026</span><h2>${t('我参与的部分','My contribution')}</h2><p>${t('在启元实验室与天数智芯的联合培养实习中，我参与 NineToothed 的工具开发、教学演示与合作研究。','During joint training at Qiyuan and Iluvatar CoreX, I contributed to NineToothed tooling, teaching demos, and collaboration research.')}</p></div><figure class="case-art"><img src="${prefix}assets/covers/ninetoothed.svg?v=transparent2" width="720" height="450" alt="${t('以计算网格为主题的编辑插画，并非项目截图','Editorial grid illustration, not a project screenshot')}"></figure></header><div class="case-lines"><section><span>01 / TOOLS</span><h3>${t('工具与移植','Tooling and porting')}</h3><p>${t('参与 NineToothed 工具及 DSL 移植。','Contributed to NineToothed tooling and DSL porting.')}</p></section><section><span>02 / TEACHING</span><h3>${t('教学材料','Teaching materials')}</h3><p>${t('整理 CUDA、推理和 Triton 的教学内容。','Prepared teaching material on CUDA, inference, and Triton.')}</p></section><section><span>03 / DEMO</span><h3>${t('WebGPU 演示','WebGPU demo')}</h3><p>${t('参与 WebGPU 教学游戏的演示。','Contributed to a WebGPU educational-game demo.')}</p></section></div><footer class="case-sources"><h2>${t('相关资料','Sources')}</h2>${links(engineering)}${cta('about.html#org-iluvatar',t('相关经历','Related experience'))}</footer></article>`;
 const socialPage=()=>`${heading('X-INSTITUTE / 2024 —',t('社会创新参与','Social innovation'),t('访谈、测试、原型与路演','Interviews, testing, prototypes and pitches'))}<div class="project-back wrap">${cta('collection.html#social',t('返回工作','Back to Work'))}</div><article class="case-study wrap"><header class="case-opening"><div><span class="eyebrow">X-INSTITUTE / 2024 —</span><h2>${t('从需求到演示','From needs to demos')}</h2><p>${h(pick(social.body)[0])}</p></div><figure class="case-art"><img src="${prefix}assets/covers/social.svg?v=transparent2" width="720" height="450" alt="${t('社会创新主题的编辑插画，并非项目截图','Editorial illustration about social innovation, not a project screenshot')}"></figure></header><p class="case-award">${t('其中「AI 助力一小帮一老」创新挑战赛的最佳创意奖属于团队。','The Best Innovation Award in the AI for the Young and the Elderly challenge was a team award.')}</p><footer class="case-sources">${cta('about.html#org-x-institute',t('相关经历','Related experience'))}${cta('about.html#honours',t('团队奖项','Team award'))}</footer></article>`;

 const publicationPage=w=>`<section class="publication-page wrap"><a class="reader-back" href="collection.html#${w.id}">${icon('arrow-left')}${t('返回工作成果','Back to Work')}</a><div class="publication-layout"><div class="publication-main"><span class="eyebrow">${t('论文记录','Publication record')} / ${h(w.year)}</span><h1>${h(pick(w.title))}</h1><p class="publication-full-title">${h(w.fullTitle||pick(w.title))}</p>${venue(w)}${metricSource(w)}<p class="reader-version">${h(pick(w.version))}</p><div class="publication-copy"><p>${h(pick(w.summary))}</p></div>${w.authors?`<p class="publication-authors">${h(w.authors)}</p>`:''}<div class="publication-links"><span class="eyebrow">${t('原始入口','Original sources')}</span>${links(w)}</div></div><figure class="publication-art"><img src="${prefix}assets/covers/${w.id}.svg?v=transparent2" alt="${h(t('这篇论文的抽象示意封面','Abstract editorial cover for this paper'))}" width="720" height="450"></figure></div></section>`;
 const newsPage=()=>`${heading(t('动态','News'),t('公开记录','Public mentions'))}<section class="news-press wrap"><div class="news-grid">${press.map(n=>`<a class="news-feature" href="${h(n.url)}" target="_blank" rel="noopener noreferrer">${n.image?`<figure><img src="${prefix}assets/news/${h(n.image)}" alt="${h(pick(n.imageAlt))}" loading="lazy"></figure>`:''}<div class="news-feature-copy"><span>${h(n.date)} · ${h(pick(n.source))}</span><h2>${h(pick(n.title))}</h2><p>${h(pick(n.summary))}</p><small>${t('查看原始记录','Open source')}${arrow()}</small></div></a>`).join('')}</div></section>`;
 const card=()=>`<section class="share-card-page wrap"><div class="share-card"><div class="share-card-top"><span>TYHUANG.HK</span><span>HONG KONG</span></div><div class="share-card-name"><h1>黄天野</h1><p>TIN-YEH HUANG</p></div><p class="card-role">${t('产品工程 · 研究 · 公共服务','Product engineering · Research · Public service')}</p><a class="share-card-email" href="mailto:tin-yeh.huang@connect.polyu.hk">tin-yeh.huang@connect.polyu.hk${arrow()}</a><div class="card-actions">${[['https://www.linkedin.com/in/tin-yeh-huang-59bba3289/','LinkedIn'],['https://github.com/Huangty5121','GitHub'],['https://scholar.google.com/citations?user=zrVCdOkAAAAJ&hl=en','Google Scholar'],['index.html',t('网站','Website')]].map(([url,label])=>`<a class="biz-btn" href="${h(url)}">${label}${arrow()}</a>`).join('')}</div></div></section>`;
 const writingModern=()=>`<article class="blog-article wrap"><header class="blog-header"><a class="reader-back" href="notes.html">${icon('arrow-left')}${t('返回个人文字','Back to Notes')}</a><div><span class="eyebrow">${h(pick(industrialNote.category))} / ${h(industrialNote.date)} / ${t('待修订','Draft')}</span><h1>${h(pick(industrialNote.title))}</h1><p>${h(pick(industrialNote.summary))}</p></div></header><figure class="blog-hero"><img src="${prefix}assets/${industrialNote.image}" alt="${t('造型与材料关系的编辑插画，并非个人作品或论文图稿','Editorial illustration of form and materials, not personal work or a research figure')}" width="1536" height="1024"><figcaption>${t('编辑插画 / 造型、材料与选择','Editorial illustration / form, material and choice')}</figcaption></figure><div class="blog-layout"><nav class="blog-toc" aria-label="${t('文章章节','Article sections')}"><span class="eyebrow">${t('在这篇文章','In this essay')}</span>${industrialNote.sections.map(sec=>`<a href="#${sec.id}"><span>${sec.number}</span>${h(pick(sec.title))}</a>`).join('')}</nav><div class="blog-body"><p class="blog-lead">${h(pick(industrialNote.lead))}</p>${industrialNote.sections.map((sec,i)=>`<section id="${sec.id}" class="blog-section"><span class="blog-section-number">${sec.number}</span><h2>${h(pick(sec.title))}</h2>${paragraphs(pick(sec.paragraphs))}</section>${i===0?`<figure class="blog-sketch"><img src="${prefix}assets/${industrialNote.sketch}" alt="${t('从造型、连接到观察的三段编辑简笔画','Three editorial sketches on form, joints and observation')}" width="2025" height="777" loading="lazy"><figcaption>${t('从形式到结构，再回到人的观察','From form to structure, then back to observation')}</figcaption></figure>`:''}`).join('')}<p class="blog-editorial-note">${h(pick(industrialNote.editorialNote))}</p></div></div></article>`;
 const reader=w=>{return `<section class="reader-page wrap"><header class="reader-bar"><a class="reader-back" href="collection.html#${w.id}">${icon('arrow-left')}${t('工作成果','Work')}</a><div class="reader-identity"><span class="eyebrow">${t('论文','Paper')} / ${h(w.year)}</span><h1>${h(pick(w.title))}</h1></div><a class="reader-open" href="${prefix}assets/${h(w.pdf)}" target="_blank" rel="noopener noreferrer">${t('打开原始 PDF','Open original PDF')}${arrow()}</a></header><div class="reader-layout"><div class="reader-canvas"><iframe class="pdf-viewer" title="${h(pick(w.title))} PDF" src="${prefix}assets/pdfjs/web/viewer.html?file=../../${h(w.pdf)}#pagemode=none&page=1&zoom=page-fit" loading="eager" allow="fullscreen"></iframe></div><aside class="reader-aside" aria-label="${t('论文简介','Paper overview')}"><span class="reader-aside-label">${t('这篇论文','About this paper')}</span><h2>${h(w.fullTitle||pick(w.title))}</h2>${venue(w)}${metricSource(w)}<p class="reader-version">${h(pick(w.version))}</p><p class="reader-lede">${h(pick(w.summary))}</p>${w.authors?`<p class="reader-authors">${h(w.authors)}</p>`:''}${links(w)}</aside></div></section>`;};
 // Hero: the owner's own Victoria Harbour night photo carries the name overlaid on top.
 return {home:()=>`<section class="landing"><figure class="hero-photo"><img src="${prefix}assets/harbour-night.jpg?v=${cacheKey}" width="2560" height="1707" alt="${t('维多利亚港的夜景，香港岛天际线在水面留下灯光倒影','Victoria Harbour at night, the Hong Kong Island skyline reflected in the water')}" fetchpriority="high"><figcaption>${t('维多利亚港 · 图片 pourya gohari / Unsplash','Victoria Harbour · photo pourya gohari / Unsplash')}</figcaption></figure><div class="wrap identity"><span class="edge-note" aria-hidden="true">個人網站 / 2026 —${lang==='zh'?' 維多利亞港':' Victoria Harbour'}</span><span class="eyebrow">${t('香港 · 产品工程在读','Hong Kong · Product Engineering student')}</span>${lang==='zh'?`<h1 class="hero-name">黄天野</h1><p class="hero-latin">TIN-YEH “HEAVEN” HUANG</p>`:`<h1 class="hero-name">Tin-Yeh Huang</h1><p class="hero-latin">黄天野 · “HEAVEN”</p>`}<p>${t('产品工程、研究与公共服务。<br>这里是我的工作与个人文字。','Product engineering, research and public service.<br>Work and writing collected here.')}</p><div class="home-paths">${cta('collection.html',t('工作成果','Work'))}${cta('notes.html',t('个人文字','Notes'))}</div><div class="landing-index"><span class="home-time"><span class="home-time-label">${t('香港时间','Hong Kong time')}</span><time data-local-time aria-label="${t('香港当地时间','Local time in Hong Kong')}">—</time><span class="home-time-zone">UTC+8</span></span></div></div></section>
 <section id="selected" class="home-selection wrap"><header><h2 class="eyebrow">${t('部分工作','Selected work')}</h2>${cta('collection.html',t('查看全部工作','All work'))}</header><div class="home-work-list">${['ninetoothed','heatwave'].map(id=>preview(entries.find(e=>e.id===id))).join('')}</div></section>
 <section class="home-notes wrap"><div><span class="eyebrow">${t('个人文字','Notes')}</span><h2>${t('工业设计与中国现代化','Industrial design and modernization')}</h2></div><p>${t('一篇关于造型、使用与制造的待修订整理稿。','A draft on form, use, and making.')}</p>${cta('notes.html',t('进入文字','Read the notes'))}<figure class="notes-material" aria-hidden="true"><img src="${prefix}assets/folio-scene-cutout.webp" alt="" width="1536" height="1024" loading="lazy"></figure></section>`,collection,about,news:newsPage,card,notes:notesPage,writingModern,engineering:engineeringPage,social:socialPage,...Object.fromEntries(papers.filter(w=>!w.pdf).map(w=>['work-'+w.id,()=>publicationPage(w)])),...Object.fromEntries(papers.filter(w=>w.pdf).map(w=>['read-'+w.id,()=>reader(w)])),missing:()=>heading('404',t('找不到这个页面','Page not found'),cta('index.html',t('返回首页','Back home')))};
}
