import {works,experiences,notes} from './content.mjs';
import {entries} from './entries.mjs';
import {education} from '../material-demo/dist/desk-background.mjs';
import {organisations,credentials} from '../material-demo/dist/desk-affiliations.mjs';
import {mapGeometry} from './map-geometry.mjs';
import {industrialNote} from './industrial-note.mjs';

export function createViews({lang,prefix,h,t,icon,a}){
 const pick=x=>x?.[lang]??x??'';
 const paragraphs=x=>(x??[]).map(p=>`<p>${h(p.replaceAll('这份 demo','本网站').replaceAll('this demo','this website'))}</p>`).join('');
 const arrow=()=>icon('arrow-up-right');
 const cta=(url,txt,cls='text-link')=>a(url,h(txt)+icon(/^(https?:|mailto:)/.test(url)?'arrow-up-right':'arrow-right'),cls);
 const papers=works.filter(w=>w.kind==='paper');
 const engineering=works.find(w=>w.id==='ninetoothed');
 const social=experiences.find(e=>e.id==='x-social');
 const sourceLabel=name=>{const parts=name.split(' / ');if(parts.length!==2)return name;return /[\u3400-\u9fff]/.test(parts[0])?t(parts[0],parts[1]):/[\u3400-\u9fff]/.test(parts[1])?t(parts[1],parts[0]):name;};
 const links=w=>`<div class="source-links">${(w.links??[]).map(([name,url])=>`<a href="${h(url)}" target="_blank" rel="noopener noreferrer">${h(sourceLabel(name))}${arrow()}</a>`).join('')}</div>`;
 const heading=(label,title,desc='')=>`<header class="page-heading wrap"><p class="eyebrow">${label}</p><h1>${title}</h1>${desc?`<p>${desc}</p>`:''}</header>`;
 const logo=o=>o.mark??(o.id==='hkcc'?'hkcc.svg':o.id==='cpce'?'cpce.png':null);
 const institutionLabel=o=>({polyu:'PolyU',tsinghua:t('清华大学','Tsinghua'),smart:'SMART',cas:'IGSNRR · CAS',polysmart:'PolySmart',iluvatar:t('天数智芯','Iluvatar CoreX'),qiyuan:t('启元实验室','Qiyuan Lab'),'royal-plaza':'Royal Plaza','x-institute':'X-Institute',hksar:t('香港特区政府','Government'),cpce:'CPCE · HKCC'})[o.id];
 const mark=o=>logo(o)?`<img src="${prefix}assets/logos/${logo(o)}" alt="" loading="lazy" width="70" height="70">`:`<span class="wordmark">${o.id==='hksar'?'HKSAR':'Qiyuan'}</span>`;
 const study=e=>`<article class="study-record" id="study-${e.id}"><time>${h(e.date)}</time><div><h3>${h(pick(e.name))}</h3><p>${h(pick(e.course))}</p><small>${h(pick(e.status))} · ${e.id==='polyu'?t('Innovation & Entrepreneurship 第二专业','Secondary major: Innovation & Entrepreneurship'):h(pick(e.extra))}</small></div></article>`;
 const role=e=>`<article class="role-record" id="record-${e.id}"><header><time>${h(e.date)}</time><h3>${h(pick(e.role))}</h3><p>${h(pick(e.name))}</p></header>${paragraphs(pick(e.body))}<div class="related">${(e.related??[]).map(id=>{const w=works.find(w=>w.id===id);return cta(w?.pdf?'read-'+id+'.html':w?.kind==='paper'?'collection.html#'+id:'project-ninetoothed.html',pick(w?.title));}).join('')}${links(e)}</div></article>`;

 const type=e=>e.kind==='paper'?t('论文','Paper'):e.kind==='writing'?t('文字 · 整理稿','Writing · Draft'):t('实践','Practice');
 const detailHref=e=>e.id==='ninetoothed'?'project-ninetoothed.html':e.id==='social'?'project-social-innovation.html':e.kind==='paper'?(e.pdf?'read-'+e.id+'.html':'work-'+e.id+'.html'):'writing.html';
 const entry=e=>`<article class="entry" id="${e.id}" data-search="${h([pick(e.title),e.fullTitle,e.context,e.year,pick(e.summary)].join(' ').toLowerCase())}" data-tags="${e.kind==='paper'?'papers':e.kind==='writing'?'writing':'projects'}" data-order="${e.order}" data-date="${e.date}"><a class="entry-link" href="${detailHref(e)}" aria-label="${h(t('查看：','View: ')+pick(e.title))}"><figure class="entry-cover"><img src="${prefix}assets/${e.cover}?v=transparent2" width="720" height="450" alt="${h(t('独立设计的示意封面：','Illustrative editorial cover: ')+pick(e.title))}" loading="lazy"></figure><div class="entry-overview"><div class="entry-label"><span>${type(e)}</span><time>${h(e.year)}</time></div><h2>${h(pick(e.title))}</h2><p class="entry-summary">${h(pick(e.summary))}</p><span class="entry-context">${h(e.context)}</span><span class="entry-prompt" aria-hidden="true">${icon('arrow-right')}</span></div></a></article>`;
 const preview=e=>`<a class="home-work-link" href="${e.id==='ninetoothed'?'project-ninetoothed.html':'read-'+e.id+'.html'}"><figure><img src="${prefix}assets/${e.cover}?v=transparent2" width="720" height="450" alt="" loading="lazy"></figure><div><span class="eyebrow">${type(e)} · ${h(e.year)}</span><h3>${h(pick(e.title))}</h3><p>${h(pick(e.summary))}</p></div>${icon('arrow-right')}</a>`;
 const home=()=>`<section class="landing wrap"><div class="identity"><span class="eyebrow">${t('香港 · 产品工程在读','Hong Kong · Product Engineering student')}</span><h1>Tin-Yeh Huang</h1><p>${t('这里放一些我参与过的工作，<br>也留一点随手写的。','Some things I have worked on,<br>and a few notes along the way.')}</p><div class="home-paths">${cta('collection.html',t('工作成果','Work'))}${cta('notes.html',t('个人文字','Notes'))}</div><div class="landing-index"><span class="local-clock"><span class="clock-dot" aria-hidden="true"></span>HONG KONG <time data-local-time aria-label="${t('香港当地时间','Local time in Hong Kong')}">—</time></span></div></div><figure class="material-scene"><img src="${prefix}assets/folio-scene-cutout.webp" alt="${t('纸、金属、半透明蓝色薄片与织物组成的层叠材料场景','An overlapping composition of paper, metal, translucent blue sheet, and fabric')}" width="1536" height="1024" fetchpriority="high"><figcaption>${t('不同的材料，同一个界面。','Different materials. One surface.')}</figcaption></figure><span class="edge-note" aria-hidden="true">PERSONAL WEBSITE / 2026</span></section>
 <section id="selected" class="home-selection wrap"><header><h2 class="eyebrow">${t('最近的工作','Selected work')}</h2>${cta('collection.html',t('查看全部工作','All work'))}</header><div class="home-work-list">${['ninetoothed','heatwave'].map(id=>preview(entries.find(e=>e.id===id))).join('')}</div></section>
 <section class="home-notes wrap"><div><span class="eyebrow">${t('工作之外','Along the way')}</span><h2>${t('一些个人文字','A few personal notes')}</h2></div><p>${t('关于形式、功能，以及设计为什么值得。','On form, function, and what makes a design worthwhile.')}</p>${cta('notes.html',t('进入文字','Read the notes'))}</section>`;
 const collection=()=>`${heading(t('工作成果','Work'),t('研究与实践','Research & practice'),t('论文、工具开发与社会创新参与。','Publications, computing tools, and social innovation.'))}<section class="collection wrap"><div class="collection-toolbar"><label>${icon('search')}<input type="search" data-search-input aria-label="${t('搜索工作成果','Search work')}" placeholder="${t('搜索标题、机构或年份','Search titles, institutions, or years')}"></label><div class="filter-controls">${[['all',t('全部','All')],['papers',t('论文','Papers')],['projects',t('实践','Practice')]].map(([id,name])=>`<button data-filter="${id}" aria-pressed="${id==='all'}">${name}</button>`).join('')}</div><label class="sort-control"><span>${t('排序','Sort')}</span><select data-sort aria-label="${t('内容排序','Entry order')}"><option value="curated">${t('编排顺序','Curated order')}</option><option value="newest">${t('年份从新到旧','Newest year first')}</option></select></label></div><p data-result-count role="status"></p><div class="index-list" data-results>${entries.filter(e=>e.kind!=='writing').map(e=>entry(e)).join('')}</div><p class="empty-state" hidden>${t('没有匹配的内容。','No matching entries.')}</p></section>`;
 const notesPage=()=>`${heading(t('个人文字','Notes'),t('一些观察与想法','Observations & thoughts'))}<section class="notes-index wrap"><a class="note-feature" href="writing-modernization.html"><div class="note-feature-copy"><span class="eyebrow">${h(pick(industrialNote.category))} / ${h(industrialNote.date)}</span><h2>${h(pick(industrialNote.title))}</h2><p>${h(pick(industrialNote.summary))}</p><span class="note-draft">${t('编辑整理稿 · 待修订','Editorial draft · Awaiting revision')}</span><span class="note-read">${t('阅读文章','Read the essay')}${icon('arrow-right')}</span></div><figure><img src="${prefix}assets/${industrialNote.image}" alt="${t('关于造型、材料与选择的编辑插画','Editorial illustration about form, material and choice')}" width="1536" height="1024" loading="lazy"></figure></a><div class="note-archive"><span class="eyebrow">${t('更多笔记','More notes')}</span>${entries.filter(e=>e.kind==='writing').map(e=>`<a class="note-list-link" href="writing.html"><span class="note-date">${h(e.year)}<small>${t('整理稿 · 待修订','Draft · Awaiting revision')}</small></span><div><h2>${h(pick(e.title))}</h2><p>${h(pick(e.summary))}</p></div>${icon('arrow-right')}</a>`).join('')}</div></section>`;
 const honours=[['2026','最佳创意奖 · 团队奖','Best Innovation Award · Team award','“AI助力一小帮一老”创新挑战赛 · UNGLEP / 深圳零一学院','“AI for the Young and the Elderly” Innovation Challenge · UNGLEP / X-Institute Shenzhen'],['2026','Ir. Dr. Wong Tit-shing Student Exchange Scholarship','Ir. Dr. Wong Tit-shing Student Exchange Scholarship','香港理工大学工程学院','Faculty of Engineering, PolyU'],['2025','Scholarship for Student Exchange','Scholarship for Student Exchange','香港理工大学 Global Engagement Office','Global Engagement Office, PolyU'],['2024','Reaching Out Award','Reaching Out Award','香港特区政府奖学基金','HKSAR Government Scholarship Fund'],['2024','ISE Department Entry Scholarship','ISE Department Entry Scholarship','香港理工大学','The Hong Kong Polytechnic University'],['2024','Study Visit Programme Scholarship','Study Visit Programme Scholarship','理大专业及持续教育学院','PolyU CPCE']];
 const tagsFor=(id,isStudy=false)=>organisations.filter(o=>(isStudy?o.study??[]:o.records).includes(id)).map(o=>o.id).join(' ')||'reviewing';
 const canonical=(html,id,isStudy=false)=>html.replace('<article ',`<article data-background-item="${id}" data-organisations="${tagsFor(id,isStudy)}" `);
 const cityFor=id=>['polyu','royal-plaza','hksar','cpce','polysmart'].includes(id)?'hk':['smart','x-institute'].includes(id)?'sz':['tsinghua','cas','qiyuan','iluvatar'].includes(id)?'bj':'other';
 const cityLL=id=>{const c=mapGeometry.cities[{'bj':'beijing','sz':'shenzhen','hk':'hong-kong'}[id]].coordinates;return `${c[1]},${c[0]}`;};
 const geographicMap=()=>`<div class="city-map"><div class="city-canvas" data-citymap role="group" aria-label="${t('机构城市地图。可拖动缩放，点城市或图上圆点筛选机构','Institution cities map. Drag to pan, zoom, and select a city to filter institutions')}" data-city-bj="${cityLL('bj')}" data-city-sz="${cityLL('sz')}" data-city-hk="${cityLL('hk')}"></div><span class="map-note">${t('城市中心点，非机构地址','City centres, not campus addresses')}</span></div>`;
 const about=()=>`${heading(t('关于我','About'),'Tin-Yeh Huang')}<section class="about-intro wrap"><div class="about-location"><span class="personal-seal" aria-hidden="true">TYH</span><span class="eyebrow">HONG KONG</span><button class="text-link" popovertarget="contact-panel">${t('联系我','Contact me')}${icon('plus')}</button></div><div class="about-copy"><p>${t('我在香港理工大学学习产品工程。学习之外，我参与研究、计算工具开发、公共服务和社会创新。','I study Product Engineering at The Hong Kong Polytechnic University. Alongside my studies, I take part in research, computing tools, public service, and social innovation.')}</p><p>${t('从实验室里的文字与图稿，到工具移植、用户访谈和社区参与，下面按机构保留这些学习和参与记录。','From text and figures in the lab to tool porting, user interviews, and community involvement, the records below follow the places where I have studied and taken part.')}</p></div></section>
 <section class="background-board wrap" id="experience"><header class="section-heading"><div><span class="eyebrow">${t('学习与参与','Study & involvement')}</span><h2>${t('在不同的地方','In different places')}</h2></div><span class="board-hint">${t('选择机构，展开记录','Select an institution to unfold the records')}</span></header><div class="city-atlas">${geographicMap()}<div class="city-index" role="group" aria-label="${t('按机构所在城市筛选','Filter by institution city')}"><div class="city-caption"><span class="eyebrow">${t('机构所在城市','Institution cities')}</span><small>${t('选择城市，再看机构与参与记录。不是个人行程。','Choose a city, then an institution and its records. This is not a travel route.')}</small></div>${[['bj',t('北京','Beijing'),t('清华 · 中科院 · 启元','Tsinghua · IGSNRR · Qiyuan')],['sz',t('深圳','Shenzhen'),'SMART · X-Institute'],['hk',t('香港','Hong Kong'),t('理大 · CPCE · 政府等','PolyU · CPCE · Government, and others')]].map(([id,label,detail])=>`<button data-city="${id}" aria-pressed="false"><span class="city-symbol" aria-hidden="true">${id==='other'?'—':'●'}</span><span>${label}<small>${detail}</small></span>${icon('arrow-right')}</button>`).join('')}</div></div><div class="directory-heading" hidden><span class="eyebrow">${t('机构','Institutions')}</span><span data-city-result><span data-city-name></span> · <span data-city-count>0</span></span></div><div class="background-layout" hidden><div class="institution-selector"><div class="organisation-choices" role="group" aria-label="${t('选择机构','Select an institution')}">${organisations.map(o=>`<button id="org-${o.id}" data-city-group="${cityFor(o.id)}" data-org="${o.id}" data-org-name="${h(pick(o.name))}" aria-label="${h(pick(o.name))}" aria-pressed="false" aria-expanded="false" aria-controls="organisation-context">${mark(o)}<span>${h(institutionLabel(o))}</span><small>${(o.study?.length||0)+o.records.length} ${t('项记录',((o.study?.length||0)+o.records.length)===1?'record':'records')}</small></button>`).join('')}</div><div class="board-secondary" hidden><button data-org="reviewing" data-org-name="${t('学术审稿','Academic peer review')}" aria-pressed="false" aria-expanded="false" aria-controls="organisation-context">${t('其他参与：学术审稿','Other involvement: academic peer review')}${icon('plus')}</button></div></div><div id="organisation-context" class="organisation-context" role="region" aria-label="${t('机构记录','Institution records')}"><header class="selected-institution" hidden><h2 data-selected-org></h2><span data-background-count role="status"></span><button data-close-org hidden aria-label="${t('返回机构列表','Back to institutions')}"><span class="close-org-text">${t('机构列表','Institutions')}</span>${icon('x')}</button></header><div class="background-record-list" id="education">${education.map(e=>canonical(study(e),e.id,true)).join('')}${experiences.map(e=>canonical(role(e),e.id)).join('')}</div><p class="board-empty" hidden>${t('选择一家机构查看对应记录。','Select an institution to read its records.')}</p></div></div></section>
 <section class="background-records wrap"><header class="section-heading"><div><span class="eyebrow">${t('另外一些记录','Further records')}</span><h2>${t('荣誉与专业资质','Recognition & credentials')}</h2></div><p class="records-intro">${t('奖项、奖学金和专业资格，按性质各放在一处。','Awards, scholarships and professional credentials, grouped by purpose.')}</p></header><div class="records-grid"><details class="record-card" id="honours"><summary><span class="record-card-icon" aria-hidden="true">✳</span><span class="record-card-label"><span class="eyebrow">01 / ${t('荣誉','Recognition')}</span><strong>${t('荣誉与奖学金','Honours & scholarships')}</strong><small>${t('团队奖项与个人奖学金，明确标注','Team award and individual scholarships, clearly distinguished')}</small></span><span class="record-card-count">06 ${icon('plus')}</span></summary><div class="record-card-body">${honours.map(([date,zh,en,dz,de])=>`<article class="study-record"><time>${date}</time><div><h3>${h(t(zh,en))}</h3><p>${h(t(dz,de))}</p></div></article>`).join('')}</div></details><details class="record-card" id="credentials"><summary><span class="record-card-icon" aria-hidden="true">⌁</span><span class="record-card-label"><span class="eyebrow">02 / ${t('资格','Credentials')}</span><strong>${t('会员与专业证书','Memberships & certification')}</strong><small>${t('专业协会会员与已取得证书','Professional memberships and completed credentials')}</small></span><span class="record-card-count">04 ${icon('plus')}</span></summary><div class="record-card-body">${credentials.map(c=>`<article class="study-record"><time>${h(c.date)}</time><div><h3>${h(c.issuer)}</h3><p>${h(pick(c.title))}</p></div></article>`).join('')}</div></details></div></section>`;
 const engineeringPage=()=>`${heading('QIYUAN × ILUVATAR COREX / 2026','NineToothed',t('工具开发、DSL 移植与教学演示','Tooling, DSL porting, and teaching demonstrations'))}<div class="project-back wrap">${cta('collection.html#ninetoothed',t('返回工作成果','Back to Work'))}</div><section class="project-body wrap"><div class="project-workspace"><div class="workspace-rail" role="group" aria-label="${t('工作内容','Work areas')}">${[['tools',t('工具与移植','Tools & porting')],['teaching',t('教学演示','Teaching demos')],['ecosystem',t('开源生态','Open-source ecosystem')]].map(([id,name],i)=>`<button data-work-area="${id}" aria-pressed="${i===0}">${String(i+1).padStart(2,'0')}<span>${name}</span>${icon('chevron-right')}</button>`).join('')}</div><div class="workspace-content">${['tools','teaching','ecosystem'].map((id,i)=>`<article data-work-panel="${id}" ${i?'hidden':''}><span class="eyebrow">${['TOOLS / ADAPTATION','LEARNING / DEMONSTRATION','RESEARCH / ECOSYSTEM'][i]}</span><h2>${[t('让工具适配计算平台','Adapting tools to a computing platform'),t('把计算内容做成演示','Turning computing topics into demonstrations'),t('合作与开源生态','Collaboration & open-source ecosystems')][i]}</h2><p>${h(pick(engineering.body)[i])}</p></article>`).join('')}<figure class="workspace-art"><img src="${prefix}assets/covers/ninetoothed.svg?v=transparent2" width="720" height="450" alt="${t('NineToothed 的抽象示意封面','Abstract editorial cover for NineToothed')}"></figure></div></div><article class="project-reading"><h2>${t('公开资料','Public resources')}</h2>${links(engineering)}${cta('about.html#org-iluvatar',t('相关实习经历','Related internship'))}<p class="version">${t('本站收录参与记录。教学游戏与演示文件尚未公开收录。','This site records the contribution. The teaching game and demonstration files are not included publicly here.')}</p></article></section>`;
 const socialPage=()=>`${heading('X-INSTITUTE / 2024 —',t('社会创新参与','Social innovation'),t('访谈、测试、原型与路演','Interviews, testing, prototypes, and presentations'))}<div class="project-back wrap">${cta('collection.html#social',t('返回工作成果','Back to Work'))}</div><article class="project-reading social-reading wrap"><div class="social-opening"><div>${paragraphs(pick(social.body))}</div><figure><img src="${prefix}assets/covers/social.svg?v=transparent2" width="720" height="450" alt="${t('社会创新项目的抽象示意封面','Abstract editorial cover for social innovation')}"></figure></div><div class="process-list">${[t('用户访谈','User interviews'),t('开发与测试','Development & testing'),t('原型与路演','Prototypes & presentations')].map((name,i)=>`<div><span>0${i+1}</span><h2>${name}</h2></div>`).join('')}</div>${cta('about.html#org-x-institute',t('相关经历','Related background'))}${cta('about.html#honours',t('团队奖项','Team award'))}</article>`;
 const writing=()=>`${heading(t('个人文字 / 整理稿','Personal writing / Draft'),h(pick(notes[0].title)))}<div class="essay-back wrap">${cta('notes.html',t('返回个人文字','Back to Notes'))}</div><article class="essay wrap">${paragraphs(pick(notes[0].paragraphs))}<p class="version">${t('据网站讨论整理，待本人修订；不是已发表文章。','Edited from website discussions, awaiting personal revision; not a published essay.')}</p></article>`;
 const publicationPage=w=>`<section class="publication-page wrap"><a class="reader-back" href="collection.html#${w.id}">${icon('arrow-left')}${t('返回工作成果','Back to Work')}</a><div class="publication-layout"><div class="publication-main"><span class="eyebrow">${t('论文记录','Publication record')} / ${h(w.year)}</span><h1>${h(pick(w.title))}</h1><p class="publication-full-title">${h(w.fullTitle||pick(w.title))}</p><p class="reader-version">${h(pick(w.version))}</p><div class="publication-copy">${paragraphs(pick(w.body))}</div>${w.authors?`<p class="publication-authors">${h(w.authors)}</p>`:''}<div class="publication-links"><span class="eyebrow">${t('原始入口','Original sources')}</span>${links(w)}</div></div><figure class="publication-art"><img src="${prefix}assets/covers/${w.id}.svg?v=transparent2" alt="${h(t('这篇论文的抽象示意封面','Abstract editorial cover for this paper'))}" width="720" height="450"><figcaption>${t('编辑插图，不是论文图稿','Editorial illustration, not a research figure')}</figcaption></figure></div></section>`;
 const writingModern=()=>`<article class="blog-article wrap"><header class="blog-header"><a class="reader-back" href="notes.html">${icon('arrow-left')}${t('返回个人文字','Back to Notes')}</a><div><span class="eyebrow">${h(pick(industrialNote.category))} / ${h(industrialNote.date)} / ${t('待修订','Draft')}</span><h1>${h(pick(industrialNote.title))}</h1><p>${h(pick(industrialNote.summary))}</p></div></header><figure class="blog-hero"><img src="${prefix}assets/${industrialNote.image}" alt="${t('造型与材料关系的编辑插画，并非个人作品或论文图稿','Editorial illustration of form and materials, not personal work or a research figure')}" width="1536" height="1024"><figcaption>${t('编辑插画 / 造型、材料与选择','Editorial illustration / form, material and choice')}</figcaption></figure><div class="blog-layout"><nav class="blog-toc" aria-label="${t('文章章节','Article sections')}"><span class="eyebrow">${t('在这篇文章','In this essay')}</span>${industrialNote.sections.map(sec=>`<a href="#${sec.id}"><span>${sec.number}</span>${h(pick(sec.title))}</a>`).join('')}</nav><div class="blog-body"><p class="blog-lead">${h(pick(industrialNote.lead))}</p>${industrialNote.sections.map((sec,i)=>`<section id="${sec.id}" class="blog-section"><span class="blog-section-number">${sec.number}</span><h2>${h(pick(sec.title))}</h2>${paragraphs(pick(sec.paragraphs))}</section>${i===0?`<figure class="blog-sketch"><img src="${prefix}assets/${industrialNote.sketch}" alt="${t('从造型、连接到观察的三段编辑简笔画','Three editorial sketches on form, joints and observation')}" width="2025" height="777" loading="lazy"><figcaption>${t('从形式到结构，再回到人的观察','From form to structure, then back to observation')}</figcaption></figure>`:''}`).join('')}<p class="blog-editorial-note">${h(pick(industrialNote.editorialNote))}</p></div></div></article>`;
 const reader=w=>{const body=pick(w.body);return `<section class="reader-page wrap"><header class="reader-bar"><a class="reader-back" href="collection.html#${w.id}">${icon('arrow-left')}${t('工作成果','Work')}</a><div class="reader-identity"><span class="eyebrow">${t('论文','Paper')} / ${h(w.year)}</span><h1>${h(pick(w.title))}</h1></div><a class="reader-open" href="${prefix}assets/${h(w.pdf)}" target="_blank" rel="noopener noreferrer">${t('打开原始 PDF','Open original PDF')}${arrow()}</a></header><div class="reader-layout"><div class="reader-canvas"><iframe class="pdf-viewer" title="${h(pick(w.title))} PDF" src="${prefix}assets/pdfjs/web/viewer.html?file=../../${h(w.pdf)}#pagemode=none&page=1&zoom=page-fit" loading="eager" allow="fullscreen"></iframe></div><aside class="reader-aside" aria-label="${t('论文简介','Paper overview')}"><span class="reader-aside-label">${t('这篇论文','About this paper')}</span><h2>${h(w.fullTitle||pick(w.title))}</h2><p class="reader-version">${h(pick(w.version))}</p>${body[0]?`<p class="reader-lede">${h(body[0])}</p>`:''}<details class="reader-more"><summary>${t('参与内容与补充信息','Contribution & details')}${icon('plus')}</summary>${paragraphs(body.slice(1))}${w.authors?`<p class="reader-authors">${h(w.authors)}</p>`:''}</details>${links(w)}</aside></div></section>`;};
 return {home,collection,about,notes:notesPage,writing,writingModern,engineering:engineeringPage,social:socialPage,...Object.fromEntries(papers.filter(w=>!w.pdf).map(w=>['work-'+w.id,()=>publicationPage(w)])),...Object.fromEntries(papers.filter(w=>w.pdf).map(w=>['read-'+w.id,()=>reader(w)])),missing:()=>heading('404',t('找不到这个页面','Page not found'),cta('index.html',t('返回首页','Back home')))};
}
